name: Azure CLI

on: 
  workflow_dispatch:
  # pull_request:
  #     branches:
  #       - main
  # push:

permissions:
  id-token: write
  contents: read

jobs:
  azure-cli-calls:
    runs-on: ubuntu-latest
    steps:
      - name: 'Azure CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run azure cli commands'
        run: |
          az account show
          az group list

      - name: 'Create group, vault and secrets'
        run: |
          LOCATION="westus"
          GROUP="tempGroup-20230602"
          VAULT="tempVault-20230602"
          
          az group create --name $GROUP --location $LOCATION
          az keyvault create --name $VAULT --resource-group $GROUP --location $LOCATION
          az keyvault secret set --vault-name $VAULT --name "example1" --value "example1secretvalue"
          az keyvault secret set --vault-name $VAULT --name "example2" --value "example2secretvalue"

      - name: 'Get secrets'
        id: azure-keyvault-secrets
        run: |
          secrets_get=(example1 example2)
          for secret_get in ${secrets_get[@]}
          do
            value=$(az keyvault secret show --name $secret_get --vault-name $VAULT --query value --output tsv)
            echo "::add-mask::$value"
            echo "$secret_get=$value" >> $GITHUB_OUTPUT
          done

      - name: Create resource groups with secret values # to know the secret values are obtained
        run: |
          az group Create --name ${{ steps.azure-keyvault-secrets.outputs.example1 }} --location $LOCATION
          az group Create --name ${{ steps.azure-keyvault-secrets.outputs.example2 }} --location $LOCATION

          