name: Javascript versioned github action

on:
  push:
    branches: [master] #change to main to make it run

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: shdfreeman/hello-world-javascript-action@v1.4
        with:
          who-to-greet: 'Joe Blow'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"